### ISSUE TITLE
introduction and first glance high-level thoughts

### ISSUE THREAD

**Issue by JessicaS11** [nasa/harmony-py#13]
Hello! I'm Jessica, and @asteiker and I have been chatting about this awesome new library. I'm the lead developer for [icepyx](https://github.com/icesat2py/icepyx), which leverages NSIDC's API for programmatic access to ICESat-2 data. I'd encourage you to check out our code base, as many of the tools I've developed there could readily be moved to a higher level library like this one (they'd just need some generalization where I've made them ICESat-2 specific and probably some transition to better practices since I based them primarily on one NSIDC data access notebook from a couple years ago). I'd be happy to help build on those tools here and then leverage them within icepyx as appropriate. I took a look at your [Harmony introduction notebook](https://harmony.earthdata.nasa.gov/notebook-example.html) and wanted to provide some high level first thoughts about where it looks like harmony-py is going and how that might align with icepyx dev goals (and with the acknowledgement that some of these things might already be in the works).

As it shows currently, the notebook showcases functionality that I would argue is too low level for most science users. For instance, functions such as `setup_earthdata_login_auth` should be wrapped entirely under the hood. I suspect this is the path that particular function is headed on, but that's less clear as you go and to my eye, there's a lot of code here the user should never see. For a case in point, check out the icepyx modules for `granules` and `variables` (https://github.com/icesat2py/icepyx/tree/development/icepyx/core). Most users don't even know they exist to handle granule searches/availability and variable-based subsetting. Inputs for data orders and downloads are validated and formatted automatically for the user in `API_formatting.py`, so they can enter the date as a string and not worry about it being put into the proper url string format or dictionary with the appropriate key to submit. Preferred submission params are used by default, with the option for the user to edit them by updating the relevant parameter dictionary stored with the search parameters. For most use cases, users interact with just a single `query` object, which includes properties that return pretty-formatted abridged and full information about the datasets, what subsetting options are available, and what granules meet their search criteria. I'm excited for the possibilities being opened by having a python library specifically aimed at easier programmatic access for NASA datasets and eager to chat with folks about how our work can be complimentary!

**Comment by rwat** [comment]
Jessica -

Thank you for the feedback. The Harmony introduction notebook using the Harmony API directly is indeed lower-level than what we intend for harmony-py. The latest harmony-py design document is the closest approximation to how we would like harmony-py to work in a 1.0 release:

https://github.com/nasa/harmony-py/blob/master/design/checkpoint_03/harmony_py.ipynb

We actually used icepyx documentation (recommended by @asteiker) as a starting point during the design process. Development is still early stages and I believe we'll try to keep most of the functionality within Harmony itself (server-side). To that end and to a large extent we are designing harmony-py around Harmony's OGC Coverages API with a goal of making Harmony easier to use. Another service that's influencing harmony-py is the [CMR](https://earthdata.nasa.gov/eosdis/science-system-description/eosdis-components/cmr) and their python wrapper: 

https://github.com/nasa/eo-metadata-tools/tree/master/CMR/python

Harmony also uses the CMR directly but we'd like to e.g. allow data generated by the CMR python wrapper be valid input to harmony-py. We plan to contribute to their library on an as-needed basis.

The aforementioned design document doesn't capture all of our discussions and design points but we'd appreciate any feedback you would be able to provide. I'll take a look at the icepyx code as well - to be continued!

**Comment by JessicaS11** [comment]
Hello @rwat! Thanks!

> The latest harmony-py design document is the closest approximation to how we would like harmony-py to work in a 1.0 release

I remember seeing this (now that you sent the link) but apparently had the wrong tab open when I re-looked to say hello yesterday. Thanks for pointing me in the right direction.

CMR and their python wrapper are on my list of things to look into using for icepyx; it's great to have these shared resources being developed!

Now that I've taken a look at the design document you linked, I have a high level question about the class names suggested (Request, Client, Job). I know that when I first got into the software development side of things these terms were very confusing to me. I now have a much better understanding of them and can see why they were chosen, but in my experience few data users have any idea what's happening within the API to get them their data (and they don't care, generally, so long as it works). I'm wondering what the implications of this terminology are for new user understanding (and also potentially as a source of confusion if they've used Python's requests library or set up a Client with dask). I know that icepyx suffers from a lack of clarity in some of its variable naming that keeps newer would-be developers from onboarding as effectively. That curiosity aside, I'm quite excited by the plans laid out for harmony-py and look forward to continuing the conversation!

**Comment by rwat** [comment]
Hi Jessica -

You raise a very valid point that directly relates to software library design and how we define the goals for the software we write: is the library approachable to the people we hope will use it and does it meet their needs?

If we boil down the library into a mix of 'nouns' and 'verbs', meaning the entities we introduce and the actions that may be taken with or upon them, how numerous and different they are relative to a person's previous experiences correlates to the cognitive overhead imposed on those individuals. The ultimate goal of writing this and similar software is to do science, to do real work, and while that requires no small amount of knowledge on the part of people doing that work, we certainly don't want to increase their tasks' incidental complexity vis-à-vis library and code machinations more than is necessary to reach the desired level of utility and sophistication (options, capability, etc.) Those tradeoffs aren't always 1:1; when it's less it can demonstrate the real art of writing software.

We also work under limitations such as the necessity (and benefit!) of group consensus, integrating with existing software and APIs, and perhaps most of all limited timeframes - I'm sure your well-acquainted with those, too.

I think we're hoping that documentation, specifically Jupyter notebooks showing various use-cases, not only communicate library concepts and how they're used but do so quickly and with a minimum of friction. We may need to remain flexible and adjust course based on feedback, including the feedback you've provided.

Kevin's done a good job on Harmony-706 which will get merged into 'master' soon. It's not the library's final form but feel free to check out https://github.com/nasa/harmony-py/blob/HARMONY-706/examples/basic.ipynb
for more detail on where things are headed.

We look forward to your feedback as we make future changes.

**Comment by vinnyinverso** [comment]
Looking forward to continuing these discussions. Hoping to set up a call between the Harmony team and some folks that are supporting icepyx, per a recent conversation with Amy.
