### ISSUE TITLE
What is the minimum python version?

### ISSUE THREAD

**Issue by jhkennedy** [nasa/harmony-py#78]
It's unclear what the minimum Python version should be for `harmony py as it's reported differently in various places:
* The `setup.py` states Python 3.6+: https://github.com/nasa/harmony-py/blob/main/setup.py#L61
* The "Using Harmony Py" section of the README list Python 3.8+: https://github.com/nasa/harmony-py?tab=readme-ov-file#using-harmony-py
* The "Running Examples & Developing on Harmony Py" section of the README lists Python 3.7+: https://github.com/nasa/harmony-py?tab=readme-ov-file#running-examples--developing-on-harmony-py

Since Python 3.6 and 3.7 are [EOL](https://devguide.python.org/versions/), I suggest aligning everything on 3.8+.

**Comment by vinnyinverso** [comment]
I added an internal ticket for this as well. Thanks for pointing this out. We'll continue to discuss/provide updates here.
