### ISSUE TITLE
Regrid of SWOT L2 Data with Harmony

### ISSUE THREAD

**Issue by nilsleh** [nasa/harmony-py#90]
I came across [this deprecated tutorial](https://github.com/podaac/tutorials/blob/master/notebooks/l2-regridding/reprojection%20notebook.ipynb) about a possible approach to regrid L2 data.

I want to work with SWOT L2 data that comes in the following format:

![image](https://github.com/user-attachments/assets/68a0b79c-e9a4-460b-b94a-63679fc55c23)

Additionally, I would like to pair the SWOT L2 data with other data that comes on a regular grid, exemplary in the dimensions of lat/lon:

![image](https://github.com/user-attachments/assets/be5f9c7c-990f-436a-abbe-b2a2558e6b79)

Essentially, I would be amazing if I could obtain a composite similar to the one shown [here](https://sealevel.jpl.nasa.gov/data/along-track-nrt-data/?page=0&per_page=3&order=publish_date+desc&search=&fancybox=true&condition_1=2024%3Ayear&category=204) (but with L2 SWOT data)

![image](https://github.com/user-attachments/assets/d4e3bd7a-cbf9-4140-bbe3-eb5b89263d91)

I am therefore wondering whether you can give me any pointers and suggestions for python tools/scripts that could achieve this. Thanks in advance!

**Comment by vinnyinverso** [comment]
@nilsleh we currently don't have this capability yet via harmony and harmony-py but a related service was under development--reusing that code might be helpful https://github.com/nasa/harmony-swath-projector. 

In the meantime, the earthdata forum https://forum.earthdata.nasa.gov and PO.DAAC's GitHub would be good places to engage on other tool recommendations https://github.com/podaac/tutorials/issues. The DAAC is usually the best resource on those types of questions. 

Best of luck! Sorry I don't have a perfect answer for you, but I hope the folks at PO.DAAC can point you in the right direction.
